application: seattlemeshnet-nodeshot
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- datastore_admin: on

inbound_services:
- warmup
- mail


handlers:
- url: /_ah/mail/.+ 
  script: handle_incoming_email.py 
  login: admin
  
- url: /_ah/pipeline(/.*)?
  script: pipeline/handlers.py

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin
  
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /bootstrap
  script: bootstrap.py
  
- url: /.*
  script: djangoappengine/main/main.py

